---
author:
  - Richard Preetz
  - Julius Greifenberg
  - Julika Hülsemann
  - Andreas Filser
title: 'Moving Back to the Parental Home in Times of COVID-19: Consequences for Students’ Life Satisfaction'
date: '2022-01-15'
publishDate: '2022-01-15'
publication_types: 
- "2"
links:
 - icon: file-pdf
   icon_pack: fas
   name: PDF
   url:  'https://www.mdpi.com/1660-4601/19/17/10659'
 - icon: doi
   icon_pack: ai
   name: Publication
   url:  'https://doi.org/10.3390/ijerph191710659'

tags:
- Boomeranging
- Covid19
- Life Satisfaction
- Living Arrangements
- Returning Home
- Transition To Adulthood
publication: '*International Journal of Environmental Research and Public Health* 19(17)'
subtitle: 'International Journal of Environmental Research and Public Health'
---
#### Abstract
Residential independence from parents is a key marker for young adults’ transition to adulthood. Losing this independence by returning to the parental home marks a regression of adult development with negative implications for returnees’ subjective wellbeing. This paper investigates how a return to the parental home during the COVID-19 pandemic affects the life satisfaction of university students. We used nationwide survey data from German university students (N = 913) to analyze differences in life satisfaction for those who did or did not return to their parental homes. Our results revealed two main findings. First, university students who moved back to their parental home reported significantly lower life satisfaction than those who remained living independently. Second, the association between moving back and life satisfaction varied by age. A return to the parental home was more detrimental to older students’ life satisfaction, while students aged 24 or younger did not experience a significant decrease when moving back to the parental home. We discuss the implications of our findings in the context of young adults’ subjective wellbeing during the COVID-19 pandemic.
 
**[Back to publication list](/publication)**
