---
author:
  - Andreas Filser
  - Pascal Achard
  - Corinna Frodermann
  - Dana Müller
  - Sander Wagner
title: 'Stratification of Post-Birth Labour Supply in a High- and Low- Maternal Employment Regime'
date: '2026-02-15'
publishDate: '2026-02-15'
publication_types: 
- "2"
links:
 - icon: file-pdf
   icon_pack: fas
   name: PDF
   url:  'https://www.sciencedirect.com/science/article/pii/S0276562426000144'
 - icon: doi
   icon_pack: ai
   name: Publication
   url:  'https://doi.org/10.1016/j.rssm.2026.101133'

tags:
- Administrative Data
- Employment
- Event Study
- France
- Germany
- Motherhood
- Motherhood Penalty
- Stratification
publication: '*Research in Social Stratification and Mobility*'
subtitle: 'Research in Social Stratification and Mobility'
---
#### Abstract
This paper compares the magnitude and stratification of motherhood employment penalties in France and Germany, two countries with contrasting institutional orientations towards maternal employment. While prior research has documented cross-national variation in the size of motherhood penalties, less is known about how macro-level contexts shape their stratification across socioeconomic groups. Using harmonized administrative employment data on 18,948 French and 72,632 German mothers, who were employed prior to first birth between 1997 and 2014, we estimate labour market participation trajectories for five years following childbirth. Across both countries, women with higher pre-birth income, higher education, and employment in higher-wage firms experience substantially smaller reductions in labour supply, with income emerging as the strongest stratifying dimension. Motherhood penalties are markedly smaller in France, amounting to less than one-third of the reduction observed in Germany. Yet penalties in France are more strongly stratified: mothers in the lowest income quintile experience participation losses 3.14 times larger than mothers in the highest quintile, compared to a ratio of 1.17 in Germany. Within Germany, East German mothers face smaller but more stratified penalties than West German mothers. Finally, we test whether the macro-level pattern of larger penalties associated with weaker stratification also generalizes to 65 NUTS-2 regions. We find no systematic association between the size and stratification of motherhood penalties at the regional level. The findings suggest that institutional contexts supporting high maternal employment reduce overall penalties but pose particular challenges for mothers from lower socio-economic backgrounds who reintegrate less rapidly into the labour market.
 
**[Back to publication list](/publication)**
