---
author:
  - Corinna Frodermann
  - Andreas Filser
  - Ann-Christin Bächmann
title: 'Parental leave of married couples: Mothers tend to return to the labour market faster when their partners take parental leave [Elternzeiten von verheirateten Paaren: Mütter kehren meist schneller auf den Arbeitsmarkt zurück, wenn ihre Partner Elternzeit nehmen]'
date: '2023-02-15'
publishDate: '2023-02-15'
publication_types: 
- "2"
links:
 - icon: file-pdf
   icon_pack: fas
   name: PDF
   url:  'https://iab.de/publikationen/publikation/?id=13157951'
 - icon: doi
   icon_pack: ai
   name: Publication
   url:  'https://doi.org/10.48720/IAB.KB.2301'

tags:
- ⛔ No Doi Found
- Berufsrückkehrerinnen
- Dauer
- Elternzeit
- Erwerbsunterbrechung
- Geschlechtsspezifische Faktoren
- Inanspruchnahme
- Mütter
- Väter
publication: '*IAB-Kurzbericht* 1(2023), 1--8'
subtitle: 'IAB-Kurzbericht'
---
#### Abstract
Following the parental leave benefit reform in 2007, the share of fathers in Germany who interrupt their employment after the birth of a child has been rising. This greater involvement of fathers is also accompanied by a faster return to the labour market of mothers. However, an analysis of couple-level parental leave patterns shows that for many married couples, it is still only the mother who interrupts her employment, while the majority of fathers do not take any parental leave. When fathers do take parental leave, it is primarily for a maximum of two months. Overall, we find that married couples in Germany are still far from sharing the burden of family-related employment interruptions equally.
 
**[Back to publication list](/publication)**
